env: local
http:
  host: 0.0.0.0
  # host: 127.0.0.1
  port: 8291
security:
  api_sign:
    app_key: 123456
    app_security: 123456
  jwt:
    key: QQYnRFerJTSEcrfB89fw8prOaObmrch8
data:
  db:
    # user:
    #   driver: sqlite
    #   dsn: storage/nunu-test.db?_busy_timeout=5000
    user:
      driver: mysql
      dsn: root:123456@tcp(host.docker.internal:3380)/user?charset=utf8mb4&parseTime=True&loc=Local
  #    user:
  #      driver: postgres
  #      dsn: host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Asia/Shanghai
  redis:
    addr: host.docker.internal:6379
    password: ""
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
  mongo:
    uri: mongodb://root:123456@localhost:27017
log:
  log_level: debug
  mode: both               #  file or console or both
  encoding: console           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
r2_aws:
  access_key_id: 17fad69440709b6a9f7982dbe95124dc
  secret_access_key: 35640b0a24b81e25eab93a5dad5a2c5bb59f6401e6e9a2437ed6b3db1b9e5fae
  region: auto
  session_token: 
  file_url: https://pub-cee4430bd1ef46588b9b587cffa3c62e.r2.dev/
  account_id: b27dd422b6edd37f3e65d02ef95c68bf
  bucket: plhh