services:
  mysql:
    image: mysql:8.0.39
    restart: unless-stopped
    ports:
      - 3380:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Shanghai
    command:
      - --default-authentication-plugin=caching_sha2_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    # volumes:
    #   - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p 123456"]
      interval: 10s
      timeout: 5s
      retries: 5
    # volumes:
    #   - ./data/mysql/user:/var/lib/mysql
    #   - ./conf/mysql/conf.d:/etc/mysql/conf.d
  cache-redis:
    image: redis:6-alpine
    hostname: cache-redis
    volumes:
      - ./data/redis/cache/:/data
      - ./conf/redis/cache/redis.conf:/etc/redis/redis.conf
    ports:
      - 6350:6379
    command: ["redis-server","/etc/redis/redis.conf"]
